# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ciderbox < Formula
  desc "Apple-native throwaway dev environments using container CLI"
  homepage "https://ciderbox.dev"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mentholmike/ciderbox/releases/download/v1.0.0/ciderbox_darwin_amd64_v1.0.0.tar.gz"
      sha256 "ed578553f87eeb68b9e574b025b74ed4577e1ec0b085ca5c095877a197116b91"

      define_method(:install) do
        bin.install "ciderbox"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mentholmike/ciderbox/releases/download/v1.0.0/ciderbox_darwin_arm64_v1.0.0.tar.gz"
      sha256 "9c74fdab7509a669318962c201236b1ca74934a38613602f429e0ce7f6980f00"

      define_method(:install) do
        bin.install "ciderbox"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mentholmike/ciderbox/releases/download/v1.0.0/ciderbox_linux_amd64_v1.0.0.tar.gz"
      sha256 "985d4531f1156b60f78c39f8975497617e15179d490032a3f67b171b04ce88db"
      define_method(:install) do
        bin.install "ciderbox"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mentholmike/ciderbox/releases/download/v1.0.0/ciderbox_linux_arm64_v1.0.0.tar.gz"
      sha256 "e0a8e252140a62110232d5159909e41fc8137af92ed92d0675cb282becbb9e4a"
      define_method(:install) do
        bin.install "ciderbox"
      end
    end
  end

  test do
    system bin/"ciderbox", "--version"
  end
end
