# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ciderbox < Formula
  desc "Apple-native throwaway dev environments using container CLI"
  homepage "https://ciderbox.dev"
  version "1.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mentholmike/ciderbox/releases/download/v1.2.1/ciderbox_1.2.1_darwin_amd64.tar.gz"
      sha256 "PLACEHOLDER_INTEL_SHA256"

      define_method(:install) do
        bin.install "ciderbox"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mentholmike/ciderbox/releases/download/v1.2.1/ciderbox_1.2.1_darwin_arm64.tar.gz"
      sha256 "PLACEHOLDER_ARM_SHA256"

      define_method(:install) do
        bin.install "ciderbox"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mentholmike/ciderbox/releases/download/v1.2.1/ciderbox_1.2.1_linux_amd64.tar.gz"
      sha256 "PLACEHOLDER_LINUX_AMD64_SHA256"
      define_method(:install) do
        bin.install "ciderbox"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mentholmike/ciderbox/releases/download/v1.2.1/ciderbox_1.2.1_linux_arm64.tar.gz"
      sha256 "PLACEHOLDER_LINUX_ARM64_SHA256"
      define_method(:install) do
        bin.install "ciderbox"
      end
    end
  end

  test do
    system bin/"ciderbox", "--version"
  end
end
